name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: |
        dotnet tool restore 
        dotnet restore
    - name: Build
      run: dotnet build --nologo --configuration Release --no-restore /WarnAsError
    - name: Test
      run: dotnet test --nologo --no-restore --verbosity minimal
    - name: Notify Slack on failure
      uses: 8398a7/action-slack@v2
      if: failure()
      with:
        status: ${{ job.status }}
        text: ${{ env.GITHUB_REF }} Build and Test failure !!!
        author_name: ${{ env.GITHUB_REPOSITORY }} ${{ env.GITHUB_WORKFLOW }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
